services:
  - type: web
    name: thinkboard
    env: node
    buildCommand: npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGO_URI
        placeholder: "Your MongoDB Atlas connection URI"
      # Optional Rate Limiter variables (bypassed if not provided)
      - key: UPSTASH_REDIS_REST_URL
        placeholder: "Optional: Your Upstash Redis URL"
      - key: UPSTASH_REDIS_REST_TOKEN
        placeholder: "Optional: Your Upstash Redis REST Token"
